[tool.ruff]
line-length = 120
target-version = "py39"
exclude = [
    "motion_capture",
    "tests/data",
    ".eggs",
    ".git",
    ".ruff_cache",
    "__pypackages__",
    "buck-out",
    "build",
    "dist",
]


[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "N", "B", "C4", "SIM"]
